import React from 'react';
import { RouteComponentProps, withRouter } from 'react-router-dom';
import { UpdateProfileFunc, UserProfile } from './models';

interface ProfileProps extends RouteComponentProps {
  updated: UpdateProfileFunc;
  user: UserProfile;
}

/**
 * Component for editing a user profile.
 * @returns
 */
class Profile extends React.Component<ProfileProps, UserProfile> {
  constructor(props: ProfileProps) {
    super(props);
    this.state = { ...props.user };
  }

  handleNameChange = (ev: React.ChangeEvent<HTMLInputElement>) => {
    this.setState({ name: ev.target.value });
  };

  setImg = (id: number) => {
    this.setState({ img: id });
  };

  saveProfile = () => {
    this.props.updated(this.state);
    this.goBack();
  };

  goBack = () => {
    this.props.history.push('/assets');
  };

  render() {
    return (
      <div>
        <div className="md:flex md:items-center mb-6">
          <div className="md:max-w-1/3">
            <label
              className="block text-gray-500 md:text-right mb-1 md:mb-0 pr-4"
              htmlFor="user-name"
            >
              Name
            </label>
          </div>
          <div className="md:w-1/2">
            <input
              className="bg-gray-100 appearance-none border-2 border-gray-100 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500"
              id="user-name"
              type="text"
              value={this.state.name}
              onChange={this.handleNameChange}
            />
          </div>
        </div>
        <div className="text-center pb-20 mb-8">
          {[...Array(18)].map((_, i) => (
            <img
              className={`inline-block w-36 m-2 cursor-pointer ${
                i === this.state.img && 'border-8 border-blue-500 shadow-xl'
              }`}
              key={i}
              onClick={() => this.setImg(i)}
              src={`img/${i}.jpg`}
              alt="AI-generated user"
            />
          ))}
          <div className="italic text-left my-4 text-sm text-gray-700">
            Images are generated by AI, courtesy of{' '}
            <a
              className="underline"
              href="https://thispersondoesnotexist.com/"
              target="_blank"
              rel="noreferrer"
            >
              thispersondoesnotexist.com
            </a>
            .
          </div>
        </div>
        <div className="bg-gray-100 fixed bottom-0 left-0 right-0 py-5 px-20 text-right shadow pr-20">
          <button className="mr-4 py-1.5 px-6" onClick={this.goBack}>
            Cancel
          </button>
          <button className="primary py-1.5 px-6" onClick={this.saveProfile}>
            Save
          </button>
        </div>
      </div>
    );
  }
}

export default withRouter(Profile);
